#!/usr/bin/env python3
"""
Generate drug discovery reports from templates.

Usage:
    python generate_report.py dossier EGFR --format pdf --output reports/
    python generate_report.py brief "EGFR inhibitors" --template competitor-brief
    python generate_report.py gng project-KRAS --format ppt
"""

import argparse
import json
import os
import sys

if sys.platform == "win32":
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8")
from datetime import datetime
from typing import Optional, Dict, Any
from pathlib import Path


class ReportGenerator:
    """Generate drug discovery reports from templates."""

    def __init__(self, report_type: str, query: str):
        self.report_type = report_type.lower()
        self.query = query
        self.template_dir = Path(__file__).parent.parent / "templates"
        self.output_format = "markdown"

    def load_template(self, template_name: Optional[str] = None) -> str:
        """Load report template."""
        if template_name:
            template_path = self.template_dir / f"{template_name}.md"
        else:
            # Map report type to template
            template_map = {
                "dossier": "target-dossier",
                "target-dossier": "target-dossier",
                "brief": "competitor-brief",
                "competitor-brief": "competitor-brief",
                "gng": "go-no-go",
                "go-no-go": "go-no-go",
                "weekly": "weekly-update",
                "weekly-update": "weekly-update"
            }
            template_name = template_map.get(self.report_type, "target-dossier")
            template_path = self.template_dir / f"{template_name}.md"

        try:
            with open(template_path, 'r') as f:
                return f.read()
        except FileNotFoundError:
            print(f"Warning: Template not found at {template_path}, using default")
            return self.get_default_template()

    def get_default_template(self) -> str:
        """Get default template if file not found."""
        return """# {{ target_name }} Report

**Generated:** {{ date }}
**Query:** {{ query }}

---

## Executive Summary

{{ executive_summary }}

---

## Analysis

[Report content will be generated here]

---

*Generated by Drug Discovery Skills for Claude*
"""

    def fetch_data(self) -> Dict[str, Any]:
        """Fetch data for report based on type."""
        # Import fetchers from other skills
        sys.path.insert(0, str(Path(__file__).parent.parent))

        data = {"query": self.query, "date": datetime.now().strftime("%Y-%m-%d")}

        try:
            if self.report_type in ["dossier", "target-dossier"]:
                # Use target-profile fetcher
                from target_profile.scripts.fetch_target_data import TargetDataFetcher
                fetcher = TargetDataFetcher(self.query)
                fetched = fetcher.fetch_all(include_uniprot=True, include_chembl=True)
                data.update(fetched)

            elif self.report_type in ["brief", "competitor-brief"]:
                # Use competitor-landscape fetcher
                from competitor_landscape.scripts.fetch_competitor_data import CompetitorDataFetcher
                fetcher = CompetitorDataFetcher(self.query)
                fetched = fetcher.fetch_all(include_clinical=True)
                data.update(fetched)

            elif self.report_type in ["gng", "go-no-go"]:
                # Combine data for Go/No-Go
                from target_profile.scripts.fetch_target_data import TargetDataFetcher
                from competitor_landscape.scripts.fetch_competitor_data import CompetitorDataFetcher

                target_fetcher = TargetDataFetcher(self.query)
                competitor_fetcher = CompetitorDataFetcher(f"{self.query} inhibitors")

                data["target"] = target_fetcher.fetch_all()
                data["competition"] = competitor_fetcher.fetch_all()

                # Add Go/No-Go scoring
                data["scores"] = self.calculate_gng_scores(data)

        except Exception as e:
            print(f"Warning: Could not fetch data: {e}")
            data["fetch_error"] = str(e)

        return data

    def calculate_gng_scores(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """Calculate Go/No-Go scores."""
        # Placeholder scoring logic
        return {
            "scientific_rationale": 75,
            "differentiation": 65,
            "feasibility": 70,
            "commercial": 68,
            "ip_safety": 50,
            "overall": 66,
            "recommendation": "Go with Conditions"
        }

    def render_template(self, template: str, data: Dict[str, Any]) -> str:
        """Render template with data."""
        content = template

        # Basic replacements
        replacements = {
            "{{ date }}": datetime.now().strftime("%Y-%m-%d"),
            "{{ query }}": self.query,
            "{{ target_name }}": self.query.upper(),
            "{{ topic }}": self.query,
            "{{ project_name }}": self.query,
            "{{ week_start }}": (datetime.now()).strftime("%Y-%m-%d"),
            "{{ week_end }}": (datetime.now()).strftime("%Y-%m-%d"),
            "{{ version }}": "1.0.0"
        }

        # Add data-driven replacements
        if "data" in data:
            if "opentargets" in data.get("data", {}):
                ot = data["data"]["opentargets"]
                replacements.update({
                    "{{ gene_symbol }}": ot.get("symbol", self.query),
                    "{{ protein_name }}": ot.get("name", "N/A"),
                })

            if "uniprot" in data.get("data", {}):
                up = data["data"]["uniprot"]
                replacements.update({
                    "{{ protein_name }}": up.get("name", replacements.get("{{ protein_name }}", "N/A")),
                    "{{ amino_acid_count }}": str(up.get("length", "N/A")),
                    "{{ molecular_weight }}": str(up.get("mass", "N/A")),
                })

        # Executive summary placeholder
        replacements["{{ executive_summary }}"] = self.generate_executive_summary(data)

        # Apply replacements
        for old, new in replacements.items():
            content = content.replace(old, str(new))

        return content

    def generate_executive_summary(self, data: Dict[str, Any]) -> str:
        """Generate executive summary based on data."""
        summary_parts = [
            f"Analysis for {self.query} generated on {datetime.now().strftime('%Y-%m-%d')}."
        ]

        if "data" in data:
            if "opentargets" in data.get("data", {}):
                ot = data["data"]["opentargets"]
                if ot.get("associations"):
                    summary_parts.append(f"Found {len(ot['associations'])} disease associations.")

            if "chembl" in data.get("data", {}):
                ch = data["data"]["chembl"]
                approved_count = len(ch.get("approved_drugs", []))
                summary_parts.append(f"{approved_count} approved drugs identified.")

            if "clinical_trials" in data.get("data", {}):
                ct = data["data"]["clinical_trials"]
                study_count = ct.get("total_studies", 0)
                summary_parts.append(f"{study_count} clinical trials found.")

        return " ".join(summary_parts) + "\n\n**Key Insights:**\n- Data analysis complete\n- Review recommendations below"

    def convert_format(self, content: str, output_format: str) -> str:
        """Convert content to specified format."""
        if output_format == "markdown" or output_format == "md":
            return content

        elif output_format == "pdf":
            # Placeholder: Would use weasyprint or similar
            print("Note: PDF conversion requires additional dependencies")
            return content

        elif output_format == "ppt" or output_format == "pptx":
            # Placeholder: Would use python-pptx
            print("Note: PPT conversion requires additional dependencies")
            return content

        return content

    def generate(self, output_path: Optional[str] = None,
                 template: Optional[str] = None,
                 format: str = "markdown") -> str:
        """Generate the report."""
        print(f"\nGenerating {self.report_type} report for: {self.query}")

        # Load template
        template_content = self.load_template(template)
        print(f"✓ Loaded template")

        # Fetch data
        data = self.fetch_data()
        print(f"✓ Fetched data")

        # Render
        rendered = self.render_template(template_content, data)
        print(f"✓ Rendered template")

        # Convert format
        self.output_format = format
        formatted = self.convert_format(rendered, format)
        print(f"✓ Format: {format}")

        # Save or return
        if output_path:
            output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)

            # Add extension if not present
            if format == "pdf" and not str(output_path).endswith(".pdf"):
                output_path = output_path.with_suffix(".pdf")
            elif format == "ppt" and not str(output_path).endswith(".pptx"):
                output_path = output_path.with_suffix(".pptx")
            elif not str(output_path).endswith(".md"):
                output_path = output_path.with_suffix(".md")

            with open(output_path, 'w') as f:
                f.write(formatted)
            print(f"✓ Saved to {output_path}")
            return str(output_path)

        return formatted


def main():
    parser = argparse.ArgumentParser(description="Generate drug discovery reports")
    parser.add_argument("report_type",
                       choices=["dossier", "brief", "gng", "weekly"],
                       help="Report type to generate")
    parser.add_argument("query", help="Query string (e.g., EGFR, 'EGFR inhibitors')")
    parser.add_argument("-o", "--output", help="Output file path")
    parser.add_argument("--template", help="Template name (default: auto-detect)")
    parser.add_argument("--format", choices=["markdown", "md", "pdf", "ppt", "pptx"],
                       default="markdown", help="Output format")
    parser.add_argument("--no-fetch", action="store_true",
                       help="Skip data fetching (use template only)")

    args = parser.parse_args()

    generator = ReportGenerator(args.report_type, args.query)

    output = args.output or f"{args.report_type}_{args.query.replace(' ', '_')}"

    result = generator.generate(
        output_path=output,
        template=args.template,
        format=args.format
    )

    print(f"\n✓ Report generation complete")


if __name__ == "__main__":
    main()
